runtime: python39
entrypoint: python app.py

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  SCRAPER_TIMEOUT: "30"
  FLASK_DEBUG: "False"

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup 